services:
  - type: web
    name: biblioteca-api
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rails db:prepare
      bundle exec rails db:seed  # se você tiver seeds importantes
      RAILS_ENV=test bundle exec rails db:test:prepare
      RAILS_ENV=test bundle exec rspec
    startCommand: bundle exec puma -C config/puma.rb
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true

databases:
  - name: biblioteca-db
    databaseName: biblioteca_api_production
    plan: free