services: ##criar instancia do bd e injeta a base de dados da api
  - type: web
    name: biblioteca-api
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rails db:migrate
    startCommand: |
      bundle exec puma -C config/puma.rb
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: biblioteca-db
          property: connectionString

databases:
  - name: biblioteca-db
    plan: free