# gerar deploy no render e conectar com o banco da api
services:
  - type: web
    name: biblioteca-api
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rails db:migrate
    startCommand: |
      bundle exec puma -C config/puma.rb
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://biblioteca_db_r3jq_user:uCaMUk0lkO3vgdD1HqlScB3rdNRFY2qF@dpg-d3su1aruibrs73aj54eg-a/biblioteca_db_r3jq

databases:
  - name: biblioteca-db
    plan: free