# This file was generated by `rails generate rspec:install`.
RSpec.configure do |config|
  # Cobertura para deploy
# Cobertura focada no core da API
if ENV['COVERAGE'] != '0'
  require 'simplecov'
  SimpleCov.start do
    enable_coverage :branch

    # medir só nosso core de negócio:
    track_files 'app/models/**/*.rb'
    track_files 'app/services/**/*.rb'
    track_files 'app/policies/**/*.rb'
    track_files 'app/controllers/api/**/*.rb'

    # ignorar o resto (infra e extras)
    add_filter %w[
      /config/
      /bin/
      /db/
      /vendor/
      /spec/
      /app/channels/
      /app/jobs/
      /app/mailers/
      /app/views/
      /app/graphql/
      /app/controllers/graphql_controller.rb
    ]

    add_group 'Models',      'app/models'
    add_group 'Services',    'app/services'
    add_group 'Policies',    'app/policies'
    add_group 'Controllers', 'app/controllers/api'

    minimum_coverage 80
  end
  puts "SimpleCov started (focused)"
end


  require 'webmock/rspec'
  WebMock.disable_net_connect!(allow_localhost: true)

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Sugeridos (descomentáveis conforme necessidade)
  # config.filter_run_when_matching :focus
  # config.example_status_persistence_file_path = "spec/examples.txt"
  # config.disable_monkey_patching!
  # if config.files_to_run.one?
  #   config.default_formatter = "doc"
  # end
  # config.profile_examples = 10
  # config.order = :random
  # Kernel.srand config.seed
end
